### PR TITLE
Junit parser for Screwdriver

### PR DESCRIPTION
**Pull request by rchopde**
## Context

Open Source Screwdriver is the flagship CI/CD platform from Verizon Media. This source code publishes a shared command for Screwdriver which provides key functionality for parsing test results. This functionality provided by my source code aligns with Screwdriver's philosophy of using shared commands to extend it's capability.
This also enables open source users of Screwdriver an easier migration path from tools like Jenkins where similar functionality is provided by it's plugin infrastructure. This also aligns with Screwdriver product goal of eventually building a market place for Shared Commands.

## Objective

This source code publishes a shared command for Screwdriver which provides key functionality for parsing test results. This functionality provided by my source code aligns with Screwdriver's philosophy of using shared commands to extend it's capability.

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by tkyi** [comment]
Would prefer to have this in `screwdriver-cd-community` org or something similar
cc: @jithin1987

**Comment by jithin1987** [comment]
> Would prefer to have this in screwdriver-cd-community org or something similar

**Comment by jithine** [comment]
> Would prefer to have this in screwdriver-cd-community org or something similar

@tkyi let's keep it here. We don't want another git org at this point.

**Comment by tkyi** [comment]
@jithin1987 I don't think we should keep user-maintained repos in our org unless we plan to take ownership and maintenance over. Or we could move this repo to `screwdriver-cd-test` org, which is where our examples are and are less maintained.

**Comment by rchopde** [comment]
Changes are in PR#2. Closing this.

**Pull request closed without merging**
